export const RES_CODE = {
  __INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  __PRISMA_ERROR: 'PRISMA_ERROR',
  __UNAUTHORIZED: 'UNAUTHORIZED',
  __NOT_FOUND: 'NOT_FOUND',
  __VALIDATION_FAILED: 'VALIDATION_FAILED',

  PRISMA__DUPLICATE_VALUE: 'DUPLICATE_VALUE',

  AUTH__LOGIN_FAILED: 'LOGIN_FAILED',

  PRODUCT__GET_FAILED: 'GET_PRODUCT_FAILED',
  PRODUCT__GETS_FAILED: 'GET_PRODUCTS_FAILED',
  PRODUCT__CREATE_FAILED: 'CREATE_PRODUCT_FAILED',
  PRODUCT__UPDATE_FAILED: 'UPDATE_PRODUCT_FAILED',
  PRODUCT__DELETE_FAILED: 'DELETE_PRODUCT_FAILED',

  USER__GET_FAILED: 'GET_USER_FAILED',
  USER__GETS_FAILED: 'GET_USERS_FAILED',
  USER__CREATE_FAILED: 'CREATE_USER_FAILED',
  USER__UPDATE_FAILED: 'UPDATE_USER_FAILED',
  USER__DELETE_FAILED: 'DELETE_USER_FAILED',

  CATEGORY__GET_FAILED: 'GET_CATEGORY_FAILED',
  CATEGORY__GETS_FAILED: 'GET_CATEGORIES_FAILED',
  CATEGORY__CREATE_FAILED: 'CREATE_CATEGORY_FAILED',
  CATEGORY__UPDATE_FAILED: 'UPDATE_CATEGORY_FAILED',
  CATEGORY__DELETE_FAILED: 'DELETE_CATEGORY_FAILED',
  CATEGORY__ASSERT_NO_CIRULAR_PARENT_FAILED: 'ASSERT_NO_CIRULAR_PARENT_FAILED',

  PRODUCT_TAG__GET_FAILED: 'GET_TAG_FAILED',
  PRODUCT_TAG__GETS_FAILED: 'GET_TAGS_FAILED',
  PRODUCT_TAG__CREATE_FAILED: 'CREATE_TAG_FAILED',
  PRODUCT_TAG__UPDATE_FAILED: 'UPDATE_TAG_FAILED',
  PRODUCT_TAG__DELETE_FAILED: 'DELETE_TAG_FAILED',

  INVENTORY__GET_FAILED: 'GET_INVENTORY_FAILED',
  INVENTORY__GETS_FAILED: 'GET_INVENTORIES_FAILED',
  INVENTORY__CREATE_FAILED: 'CREATE_INVENTORY_FAILED',
  INVENTORY__UPDATE_FAILED: 'UPDATE_INVENTORY_FAILED',
  INVENTORY__DELETE_FAILED: 'DELETE_INVENTORY_FAILED',

  PRODUCT_OPTION_VALUE__GET_FAILED: 'GET_PRODUCT_OPTION_VALUE_FAILED',
  PRODUCT_OPTION_VALUE__GETS_FAILED: 'GET_PRODUCT_OPTION_VALUES_FAILED',
  PRODUCT_OPTION_VALUE__CREATE_FAILED: 'CREATE_PRODUCT_OPTION_VALUE_FAILED',
  PRODUCT_OPTION_VALUE__UPDATE_FAILED: 'UPDATE_PRODUCT_OPTION_VALUE_FAILED',
  PRODUCT_OPTION_VALUE__DELETE_FAILED: 'DELETE_PRODUCT_OPTION_VALUE_FAILED',

  PRODUCT_OPTION__GET_FAILED: 'GET_PRODUCT_OPTION_VALUE_FAILED',
  PRODUCT_OPTION__GETS_FAILED: 'GET_PRODUCT_OPTIONS_FAILED',
  PRODUCT_OPTION__CREATE_FAILED: 'CREATE_PRODUCT_OPTION_FAILED',
  PRODUCT_OPTION__UPDATE_FAILED: 'UPDATE_PRODUCT_OPTION_FAILED',
  PRODUCT_OPTION__DELETE_FAILED: 'DELETE_PRODUCT_OPTION_FAILED',

  PRODUCT_IMAGE__GET_FAILED: 'GET_PRODUCT_IMAGE_FAILED',
  PRODUCT_IMAGE__GETS_FAILED: 'GET_PRODUCT_IMAGES_FAILED',
  PRODUCT_IMAGE__CREATE_FAILED: 'CREATE_PRODUCT_IMAGE_FAILED',
  PRODUCT_IMAGE__UPDATE_FAILED: 'UPDATE_PRODUCT_IMAGE_FAILED',
  PRODUCT_IMAGE__DELETE_FAILED: 'DELETE_PRODUCT_IMAGE_FAILED',

  PRODUCT_VARIANT__GET_FAILED: 'GET_PRODUCT_VARIANT_FAILED',
  PRODUCT_VARIANT__GETS_FAILED: 'GET_PRODUCT_VARIANTS_FAILED',
  PRODUCT_VARIANT__CREATE_FAILED: 'CREATE_PRODUCT_VARIANT_FAILED',
  PRODUCT_VARIANT__UPDATE_FAILED: 'UPDATE_PRODUCT_VARIANT_FAILED',
  PRODUCT_VARIANT__DELETE_FAILED: 'DELETE_PRODUCT_VARIANT_FAILED',
};

export const RES_MESSAGE = {
  __INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  __PRISMA_ERROR: 'PRISMA_ERROR',

  PIPE__PARSE_INT_ERROR: 'Validation failed (numeric string is expected)',
  PIPE__PARSE_UUID_ERROR:
    'Validation failed {string}-${string}-${string}-${string}-${string}',

  PRISMA__DUPLICATE_VALUE: (field) => `Duplicate value for: ${field}`,

  AUTH__ACCOUNT_OR_PASSWORD_INVALID: 'Tài khoản hoặc mật khẩu không hợp lệ',
  AUTH__ACCOUNT_DOES_NOT_EXISTS: 'Tài khoản không tồn tại',
  AUTH__PASSWORD_IS_INCORRECT: 'Mật khẩu không chính xác',

  AUTH__LOGIN_SUCCESS: 'Đăng nhập thành công',
  AUTH__LOGOUT_SUCCESS: 'Đăng xuất thành công',
  USER__NOT_FOUND_ID: (id) => `user.id: ${id} không tồn tại`,
  USER__EMAIL_IS_EXISTING: 'Email đã tồn tại',

  CATEGORY__HANDLE_IS_EXISTING: (handle) =>
    `category.handle: ${handle} đã tồn tại`,
  CATEGORY__NOT_FOUND_ID: (id) => `category.id: ${id} không tồn tại`,
  CATEGORY__CIRULAR_PARENT_ERROR: 'vòng lặp',

  PRODUCT_VARIANT__SKU_IS_EXISTING: (sku) =>
    `product_variant.sku: ${sku} đã tồn tại`,
  PROUDCT_VARIANT__NOT_FOUND_ID: (id) =>
    `product_variant.id: ${id} không tồn tại`,

  PRODUCT_HANDLE_IS_EXSTING: (handle) => `product.handle: ${handle} đã tồn tại`,

  PRODUCT_OPTION__NOT_FOUND_TITLE: (title) =>
    `product_option.title: ${title} không tồn tại`,
  PRODUCT_OPTION_VALUE__NOT_FOUND_VALUE: (value) =>
    `product_option.value: ${value} không tồn tại`,

  TAG__VALUE_IS_EXISTING: (value) => `tag.value: ${value} đã tồn tại`,
  TAG__NOT_FOUND_ID: (id) => `tag.id: ${id} không tồn tại`,

  PRODUCT__NOT_FOUND_ID: (id) => `product.id: ${id} không tồn tại`,

  INVENTORY__VARIANT_ID_IS_EXISTING: (variantId) =>
    `inventory.variant_id: ${variantId} đã tồn tại`,
  INVENTORY__NOT_FOUND_ID: (id) => `inventory.id: ${id} không tồn tại`,

  PRODUCT_OPTION_VALUE__NOT_FOUND_ID: (id) =>
    `product_option_value.id: ${id} không tồn tại`,

  PRODUCT_OPTION_VALUE__VALUE_IS_EXISTING: (optionId, value) =>
    `product_option_value.value: ${optionId}.${value} đã tồn tại`,

  PRODUCT_OPTION__NOT_FOUND_ID: (id) =>
    `product_option.id: ${id} không tồn tại`,
  PRODUCT_OPTION__TITLE_IS_EXISTING: (productId, title) =>
    `product_option.title: ${productId}.${title} đã tồn tại`,

  PRODUCT_IMAGE__NOT_FOUND_ID: (id) => `product_image.id: ${id} không tồn tại`,
};
