export const RES_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',

  LOGIN_FAILED: 'LOGIN_FAILED',

  GET_USER_FAILED: 'GET_USER_FAILED',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
  DELETE_USER_FAILED: 'DELETE_USER_FAILED',
};
